project:
  type: website
  output-dir: docs
  
website:
  title: "Ravindra's Data Science Blog"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: posts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true